version: '3.7'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - kong-net
    ports:
      - "6380:6379"
